version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14.6-alpine
    container_name: postgres_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr